package writer

import (
	"fmt"
	"os"
	"strings"

	"github.com/TaurineMerge/LMS_Tages/utils/knowledge-base-test-data-generator/internal/models"
)

// SQLWriter is responsible for writing generated data to an SQL file.
type SQLWriter struct {
	file *os.File
}

// NewSQLWriter creates and opens a new SQL file for writing.
func NewSQLWriter(outputPath string) (*SQLWriter, error) {
	f, err := os.Create(outputPath)
	if err != nil {
		return nil, fmt.Errorf("failed to create output file: %w", err)
	}

	writer := &SQLWriter{file: f}
	writer.writeHeader()

	return writer, nil
}

// Close closes the underlying file.
func (w *SQLWriter) Close() {
	w.file.Close()
}

// writeHeader writes the initial SQL comments and settings.
func (w *SQLWriter) writeHeader() {
	header := `-- Test data generated by knowledge-base-test-data-generator
--
-- Disables WAL for faster inserts. Remember to re-enable if needed.
-- ALTER SYSTEM SET wal_level = 'minimal';
-- ALTER SYSTEM SET max_wal_senders = 0;

`
	w.file.WriteString(header)
}

// WriteCategory writes an INSERT statement for a Category.
func (w *SQLWriter) WriteCategory(category models.Category) error {
	stmt := fmt.Sprintf(
		"INSERT INTO knowledge_base.category_d (id, title, created_at, updated_at) VALUES ('%s', '%s', '%s', '%s');\n",
		category.ID,
		escapeSQL(category.Title),
		category.CreatedAt.Format("2006-01-02 15:04:05"),
		category.UpdatedAt.Format("2006-01-02 15:04:05"),
	)
	_, err := w.file.WriteString(stmt)
	return err
}

// WriteCourse writes an INSERT statement for a Course.
func (w *SQLWriter) WriteCourse(course models.Course) error {
	stmt := fmt.Sprintf(
		"INSERT INTO knowledge_base.course_b (id, title, description, level, visibility, category_id, created_at, updated_at) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s');\n",
		course.ID,
		escapeSQL(course.Title),
		escapeSQL(course.Description),
		course.Level,
		course.Visibility,
		course.CategoryID,
		course.CreatedAt.Format("2006-01-02 15:04:05"),
		course.UpdatedAt.Format("2006-01-02 15:04:05"),
	)
	_, err := w.file.WriteString(stmt)
	return err
}

// WriteLesson writes an INSERT statement for a Lesson.
func (w *SQLWriter) WriteLesson(lesson models.Lesson) error {
	// A simple JSON-like representation for the content blocks array.
	// PostgreSQL's JSONB capabilities will handle this.
	var contentBuilder strings.Builder
	contentBuilder.WriteString("[")
	for i, block := range lesson.Content {
		// Note: A more robust implementation would use json.Marshal
		// This is a simplified version for generating predictable SQL.
		contentBuilder.WriteString(fmt.Sprintf(
			`{"content_type": "%s", "data": "%s"}`,
			block.ContentType,
			escapeSQL(block.Data),
		))

		if i < len(lesson.Content)-1 {
			contentBuilder.WriteString(",")
		}
	}
	contentBuilder.WriteString("]")

	stmt := fmt.Sprintf(
		"INSERT INTO knowledge_base.lesson_d (id, title, course_id, content, created_at, updated_at) VALUES ('%s', '%s', '%s', '%s', '%s', '%s');\n",
		lesson.ID,
		escapeSQL(lesson.Title),
		lesson.CourseID,
		contentBuilder.String(),
		lesson.CreatedAt.Format("2006-01-02 15:04:05"),
		lesson.UpdatedAt.Format("2006-01-02 15:04:05"),
	)
	_, err := w.file.WriteString(stmt)
	return err
}

// escapeSQL escapes single quotes in a string for SQL.
func escapeSQL(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}
