#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS knowledge_base;

    -- Create Roles
    DO
    \$do\$
    BEGIN
       IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = '${KNOWLEDGE_BASE_ADMIN_USER}') THEN

          CREATE ROLE ${KNOWLEDGE_BASE_ADMIN_USER} WITH LOGIN PASSWORD '${KNOWLEDGE_BASE_ADMIN_PASSWORD}';
       END IF;
    END
    \$do\$;

    DO
    \$do\$
    BEGIN
       IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = '${KNOWLEDGE_BASE_RO_USER}') THEN

          CREATE ROLE ${KNOWLEDGE_BASE_RO_USER} WITH LOGIN PASSWORD '${KNOWLEDGE_BASE_RO_PASSWORD}';
       END IF;
    END
    \$do\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${KNOWLEDGE_BASE_ADMIN_USER}, ${KNOWLEDGE_BASE_RO_USER};
    GRANT USAGE ON SCHEMA knowledge_base TO ${KNOWLEDGE_BASE_ADMIN_USER}, ${KNOWLEDGE_BASE_RO_USER};
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA knowledge_base FOR ROLE ${POSTGRES_USER}
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${KNOWLEDGE_BASE_ADMIN_USER};
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA knowledge_base FOR ROLE ${POSTGRES_USER}
        GRANT SELECT ON TABLES TO ${KNOWLEDGE_BASE_RO_USER};

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA knowledge_base TO ${KNOWLEDGE_BASE_ADMIN_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA knowledge_base TO ${KNOWLEDGE_BASE_RO_USER};

EOSQL